name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python hello.py
  
  telegramm:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ secrets.TELEGRAM_TO }}
          echo ${{ secrets.TELEGRAM_TO }}
      - name: send message
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            qu 
            im bot