name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  sys_info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          uname
          pwd
      - name: system info
        run: lshw
  
  build:
    runs-on: ubuntu-latest
    env:
      local_env: job_print_env
    steps:
      - name: build
        run: echo "test build" >> build.txt
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: run_test
        run: echo "hello test"

  export:
    runs-on: ubuntu-latest
    steps:
      - name: run_export
        run: echo "hello export"