name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  sys_info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          uname
          pwd
      - name: system info
        run: lshw
  
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip


  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: run_test
        run: echo "hello test"

  export:
    runs-on: ubuntu-latest
    steps:
      - name: run_export
        run: echo "hello export"