name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python hello.py
  
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: levbugrov/gh_and_python
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  telegram_success:
    runs-on: ubuntu-latest
    needs: [ push_to_registry ]
    steps:
      - name: send message
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The build was successful 
            Repository: ${{ github.repository }}
            Commit message: ${{ github.event.commits[0].message }}
            by: ${{ github.actor }}
  
  telegram_fail:
    if: failure() 
    runs-on: ubuntu-latest
    needs: [ push_to_registry ]
    steps:
      - name: send message
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The build was fail
            Repository: ${{ github.repository }}
            Commit message: ${{ github.event.commits[0].message }}
            bad human: ${{ github.actor }}
